module.exports = {
	GET_GITLAB_GROUPS: 'GET_GITLAB_GROUPS',
	GET_MEISTERTASK_GROUPS: 'GET_MEISTERTASK_GROUPS',
	GET_MEISTERTASK_GROUPS_PROJECT: 'GET_MEISTERTASK_GROUPS_PROJECT',
	GET_MEISTERTASK_PROJECT_TASKS: 'GET_MEISTERTASK_PROJECT_TASKS',

	GET_GITLAB_GROUP_PROJECTS: 'GET_GITLAB_GROUP_PROJECTS',
	GET_GITLAB_PROJECTS_TASKS: 'GET_GITLAB_PROJECTS_TASKS'
};
