module.exports = {
	ADD_SUCCESS: 'ADD_SUCCESS',
	GET_SUCCESS: 'GET_SUCCESS',
	LIST_SUCCESS: 'LIST_SUCCESS',
	SET_LOADING: 'SET_LOADING',
	RESET_LOADING: 'RESET_LOADING',
	DELETE_SUCCESS: 'DELETE_SUCCESS'
};
